import { MetricCard } from '@/components/dashboard/metric-card';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, Award, BookOpenCheck, Code2, Flame, MessageSquareQuote, Sparkles, Users } from 'lucide-react';

interface ParentDashboardProps {
    children: Array<{
        id: number;
        name: string;
        learner_id: string | null;
        avatar_url: string | null;
        world: string;
        progress: number;
        level: string;
        stars: number;
        streak: number;
    }>;
    overview: { completedMissions: number; stars: number; releasedAssignments: number; htmlProjects: number };
    recentAssignments: Array<{
        id: number;
        child: string;
        assignment: string;
        status: string;
        result_released: boolean;
        score: number | null;
        maximum_score: number | null;
        teacher_feedback: string | null;
    }>;
    htmlProjects: Array<{ child: string; title: string; status: string; approvedPreview: string | null }>;
    quickActions: Array<{ label: string; href: string }>;
}

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Parent Dashboard', href: '/parent/dashboard' }];

export default function ParentDashboard({ children, overview, recentAssignments, htmlProjects, quickActions }: ParentDashboardProps) {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Parent Dashboard" />
            <div className="space-y-6 p-4 md:p-6">
                <section className="rounded-[2rem] bg-gradient-to-br from-emerald-950 via-emerald-900 to-teal-800 p-6 text-white shadow-xl md:p-8">
                    <p className="text-sm font-semibold tracking-[0.2em] text-emerald-200 uppercase">Family learning overview</p>
                    <h1 className="mt-2 text-3xl font-black tracking-tight">See progress, feedback and projects in one place</h1>
                    <p className="mt-3 max-w-3xl text-sm leading-7 text-emerald-50/85">
                        Only children linked to this account are shown. Results and teacher feedback remain hidden until they are formally released.
                    </p>
                </section>

                <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <MetricCard
                        title="Linked children"
                        value={String(children.length)}
                        description="Authorised family connections only."
                        icon={<Users className="h-5 w-5" />}
                    />
                    <MetricCard
                        title="Completed missions"
                        value={String(overview.completedMissions)}
                        description="Validated learning completions across linked children."
                        accent="from-sky-500/20 to-cyan-500/20"
                        icon={<BookOpenCheck className="h-5 w-5" />}
                    />
                    <MetricCard
                        title="Stars earned"
                        value={String(overview.stars)}
                        description="Rewards generated by the server-side progress engine."
                        accent="from-amber-500/20 to-orange-500/20"
                        icon={<Award className="h-5 w-5" />}
                    />
                    <MetricCard
                        title="HTML projects"
                        value={String(overview.htmlProjects)}
                        description={`${overview.releasedAssignments} assignment results released.`}
                        accent="from-violet-500/20 to-fuchsia-500/20"
                        icon={<Code2 className="h-5 w-5" />}
                    />
                </section>

                <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                    {quickActions.map((action) => (
                        <Link
                            key={action.href}
                            href={action.href}
                            className="group flex items-center justify-between rounded-3xl border border-emerald-100 bg-white/90 p-4 font-semibold text-emerald-950 shadow-sm transition hover:bg-emerald-50"
                        >
                            {action.label}
                            <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" />
                        </Link>
                    ))}
                </section>

                <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
                    <div className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-[0_12px_40px_rgba(38,84,63,0.08)]">
                        <h2 className="text-xl font-black">Your children</h2>
                        <div className="mt-4 grid gap-4 md:grid-cols-2">
                            {children.map((child) => (
                                <Link
                                    key={child.id}
                                    href={route('parent.children.show', child.id)}
                                    className="rounded-3xl border border-emerald-100 bg-emerald-50/50 p-5 transition hover:bg-emerald-50"
                                >
                                    <div className="flex items-center gap-4">
                                        <div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-2xl bg-white text-xl font-black text-emerald-800 shadow-sm">
                                            {child.avatar_url ? (
                                                <img src={child.avatar_url} alt="" className="h-full w-full object-cover" />
                                            ) : (
                                                child.name.slice(0, 1)
                                            )}
                                        </div>
                                        <div>
                                            <p className="font-bold text-emerald-950">{child.name}</p>
                                            <p className="text-sm text-emerald-800">
                                                {child.learner_id ?? 'Learner ID pending'} · {child.level}
                                            </p>
                                        </div>
                                    </div>
                                    <p className="mt-4 text-sm text-slate-600">Current class: {child.world}</p>
                                    <div className="mt-3 h-2 rounded-full bg-white">
                                        <div className="h-2 rounded-full bg-emerald-500" style={{ width: `${child.progress}%` }} />
                                    </div>
                                    <div className="mt-3 flex justify-between text-xs font-semibold text-emerald-800">
                                        <span>{child.progress}% journey progress</span>
                                        <span className="inline-flex items-center gap-1">
                                            <Flame className="h-3 w-3" />
                                            {child.streak} day streak
                                        </span>
                                    </div>
                                </Link>
                            ))}
                            {children.length === 0 && (
                                <p className="rounded-3xl border border-dashed p-6 text-sm text-slate-600">
                                    No children are linked to this parent account. An administrator can create the connection in School Management.
                                </p>
                            )}
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-[0_12px_40px_rgba(38,84,63,0.08)]">
                            <div className="flex items-center gap-3">
                                <MessageSquareQuote className="h-5 w-5 text-amber-700" />
                                <h2 className="text-xl font-black">Recent assignments</h2>
                            </div>
                            <div className="mt-4 space-y-3">
                                {recentAssignments.map((item) => (
                                    <div key={item.id} className="rounded-3xl bg-amber-50 p-4">
                                        <p className="font-semibold text-amber-950">{item.assignment}</p>
                                        <p className="mt-1 text-sm text-amber-800">
                                            {item.child} · {item.status.replaceAll('_', ' ')}
                                        </p>
                                        {item.result_released ? (
                                            <p className="mt-2 text-sm font-semibold text-amber-950">
                                                Released result: {item.score}/{item.maximum_score}
                                            </p>
                                        ) : (
                                            <p className="mt-2 text-sm text-amber-800">Result not released yet.</p>
                                        )}
                                        {item.teacher_feedback && (
                                            <p className="mt-2 rounded-2xl bg-white/80 p-3 text-sm text-slate-700">{item.teacher_feedback}</p>
                                        )}
                                    </div>
                                ))}
                                {recentAssignments.length === 0 && (
                                    <p className="rounded-3xl border border-dashed p-5 text-sm text-slate-600">No assignment activity yet.</p>
                                )}
                            </div>
                        </div>
                        <div className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-[0_12px_40px_rgba(38,84,63,0.08)]">
                            <div className="flex items-center gap-3">
                                <Sparkles className="h-5 w-5 text-sky-700" />
                                <h2 className="text-xl font-black">HTML project journey</h2>
                            </div>
                            <div className="mt-4 space-y-3">
                                {htmlProjects.map((item, index) => (
                                    <div key={`${item.title}-${index}`} className="rounded-3xl bg-sky-50 p-4">
                                        <p className="font-semibold text-sky-950">{item.title}</p>
                                        <p className="mt-1 text-sm text-sky-800">
                                            {item.child} · {item.status.replaceAll('_', ' ')}
                                        </p>
                                        <p className="mt-2 text-xs font-semibold text-sky-700">
                                            {item.approvedPreview
                                                ? 'Teacher-approved private preview available'
                                                : 'Preview remains private until teacher approval'}
                                        </p>
                                    </div>
                                ))}
                                {htmlProjects.length === 0 && (
                                    <p className="rounded-3xl border border-dashed p-5 text-sm text-slate-600">No HTML project activity yet.</p>
                                )}
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </AppLayout>
    );
}
